import { useState, useEffect } from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import {
  Outlet,
  Link,
  createRootRouteWithContext,
  useRouter,
  HeadContent,
  Scripts,
} from "@tanstack/react-router";

import appCss from "../styles.css?url";
import { AuthProvider } from "@/hooks/use-auth";
import { Toaster } from "@/components/ui/sonner";

function NotFoundComponent() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-background px-4">
      <div className="max-w-md text-center">
        <h1 className="text-7xl font-bold text-foreground">404</h1>
        <h2 className="mt-4 text-xl font-semibold text-foreground">Page not found</h2>
        <p className="mt-2 text-sm text-muted-foreground">
          The page you're looking for doesn't exist or has been moved.
        </p>
        <div className="mt-6">
          <Link
            to="/"
            className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
          >
            Go home
          </Link>
        </div>
      </div>
    </div>
  );
}

function ErrorComponent({ error, reset }: { error: Error; reset: () => void }) {
  console.error(error);
  const router = useRouter();

  return (
    <div className="flex min-h-screen items-center justify-center bg-background px-4">
      <div className="max-w-md text-center">
        <h1 className="text-xl font-semibold tracking-tight text-foreground">
          This page didn't load
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Something went wrong on our end. You can try refreshing or head back home.
        </p>
        <div className="mt-6 flex flex-wrap justify-center gap-2">
          <button
            onClick={() => {
              router.invalidate();
              reset();
            }}
            className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
          >
            Try again
          </button>
          <a
            href="/"
            className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-accent"
          >
            Go home
          </a>
        </div>
      </div>
    </div>
  );
}

const themeScript = `
(function() {
  var theme = localStorage.getItem('screenmint:theme');
  if (theme === 'light') {
    document.documentElement.classList.remove('dark');
  } else {
    document.documentElement.classList.add('dark');
  }
})();
`;

export const Route = createRootRouteWithContext<{ queryClient: QueryClient }>()({
  head: () => ({
    meta: [
      { charSet: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { title: "Screenify — AI-powered Shopify app store screenshots" },
      { name: "description", content: "Upload one screenshot. Get polished Shopify app store promo images with captions, generated by AI." },
      { name: "author", content: "Screenify" },
      { property: "og:title", content: "Screenify — AI-powered Shopify app store screenshots" },
      { property: "og:description", content: "Upload one screenshot. Get polished Shopify app store promo images with captions, generated by AI." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
      { name: "twitter:title", content: "Screenify — AI-powered Shopify app store screenshots" },
      { name: "twitter:description", content: "Upload one screenshot. Get polished Shopify app store promo images with captions, generated by AI." },
      { property: "og:image", content: "https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/26ac19fa-dcbd-49a6-a12f-832ad7d2a849/id-preview-ed2f763e--c3f3b9a4-192d-41b9-8e68-13117736467d.lovable.app-1779025059476.png" },
      { name: "twitter:image", content: "https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/26ac19fa-dcbd-49a6-a12f-832ad7d2a849/id-preview-ed2f763e--c3f3b9a4-192d-41b9-8e68-13117736467d.lovable.app-1779025059476.png" },
    ],
    links: [
      { rel: "stylesheet", href: appCss },
      { rel: "preconnect", href: "https://fonts.googleapis.com" },
      { rel: "preconnect", href: "https://fonts.gstatic.com", crossOrigin: "anonymous" },
      {
        rel: "stylesheet",
        href: "https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Inter+Tight:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap",
      },
    ],
    scripts: [
      { type: "text/javascript", children: themeScript },
      { src: "https://app.lemonsqueezy.com/js/lemon.js", defer: true },
    ],
  }),
  shellComponent: RootShell,
  component: RootComponent,
  notFoundComponent: NotFoundComponent,
  errorComponent: ErrorComponent,
});

function RootShell({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body>
        {children}
        <Scripts />
      </body>
    </html>
  );
}

function RootComponent() {
  const { queryClient } = Route.useRouteContext();
  const [showCookieBanner, setShowCookieBanner] = useState(false);

  useEffect(() => {
    const consent = localStorage.getItem("screenify:cookie-consent");
    if (!consent) {
      setShowCookieBanner(true);
    }
  }, []);

  return (
    <QueryClientProvider client={queryClient}>
      <AuthProvider>
        <Outlet />
        <Toaster position="top-center" />
        
        {showCookieBanner && (
          <div className="fixed bottom-6 right-6 z-50 max-w-sm rounded-2xl border border-border/60 bg-card/85 p-5 shadow-2xl backdrop-blur-md animate-in fade-in slide-in-from-bottom-5 duration-300">
            <div className="space-y-3">
              <h4 className="font-display text-sm font-bold tracking-tight text-foreground flex items-center gap-1.5">
                🍪 Cookie Consent
              </h4>
              <p className="text-xs text-muted-foreground leading-relaxed">
                We use essential cookies to manage your sessions and secure payments. Learn more in our{" "}
                <Link to="/cookies" className="text-lime underline hover:text-[#3ECFB2] transition-colors">
                  Cookie Policy
                </Link>
                .
              </p>
              <div className="flex justify-end gap-2 pt-1">
                <button
                  onClick={() => {
                    localStorage.setItem("screenify:cookie-consent", "declined");
                    setShowCookieBanner(false);
                  }}
                  className="rounded-lg border border-border px-3 py-1.5 text-[10px] font-semibold text-muted-foreground hover:bg-card hover:text-foreground transition cursor-pointer"
                >
                  Decline
                </button>
                <button
                  onClick={() => {
                    localStorage.setItem("screenify:cookie-consent", "accepted");
                    setShowCookieBanner(false);
                  }}
                  className="rounded-lg bg-[#3ECFB2] px-3 py-1.5 text-[10px] font-semibold text-slate-950 hover:opacity-90 transition cursor-pointer"
                >
                  Accept
                </button>
              </div>
            </div>
          </div>
        )}
      </AuthProvider>
    </QueryClientProvider>
  );
}
