import { createFileRoute, Link } from "@tanstack/react-router";
import { renderLegalContent } from "@/lib/legal-formatter";

export const Route = createFileRoute("/disclaimer")({
  component: DisclaimerPage,
});

function DisclaimerPage() {
  const lastUpdated = "June 12, 2026";

  const sections = [
    {
      title: "1. AI-Generated Content Disclaimer",
      content: `Screenify utilizes generative artificial intelligence models (including OpenAI's GPT models and Google's Gemini models) to analyze screenshots and suggest marketing headlines, subheadlines, and features.
      
      You acknowledge and agree that:
      - **Content Accuracy**: AI-generated suggestions are produced probabilistically and may contain spelling mistakes, generic phrasing, grammatical errors, or factually incorrect descriptions of your application. You are solely responsible for reviewing and editing all text inside the Design Studio prior to downloading or using the creatives.
      - **Uniqueness**: The AI may output similar copywriting suggestions to different users who present similar app categories or objectives. Screenify does not guarantee that the generated copywriting will be unique to your application.`
    },
    {
      title: "2. Exclusions of Warranties & Outcomes",
      content: `The Service is provided for design facilitation purposes only. Screenify explicitly disclaims any warranties or guarantees regarding:
      - **Business Outcomes**: We do not guarantee that using Screenify will increase your app's downloads, sales, customer retention, click-through rates, active merchant counts, or revenue.
      - **App Store Approvals**: We do not guarantee that the generated templates, layout dimensions, fonts, or copywriting will meet the current or future compliance policies of the Shopify App Store. The user remains solely responsible for ensuring that all uploaded and submitted storefront images comply with Shopify's App Store guidelines.`
    },
    {
      title: "3. Intellectual Property & Trademark Responsibilities",
      content: `Because AI-assisted engines draw context from general training corpora, there is a minor risk that suggested copywriting or terms could overlap with registered trademarks, brand names, or copyrights owned by third-party companies.
      
      You represent and warrant that you will verify that all copy, slogans, logos, and layouts generated by Screenify do not infringe on the intellectual property rights of any third party before posting them to your public listings. Screenify disclaims any liability for copyright, trademark, or trade name disputes arising from AI-generated copy.`
    },
    {
      title: "4. No Legal or Professional Advice",
      content: `Any guidelines, tips, blog posts, listing scores, or audit feedback provided by Screenify (including audit feedback generated by the AI) do not constitute professional marketing, legal, or business optimization advice. You should seek independent consultation or verify listing rules directly with Shopify’s developer documentation if you require formal validation.`
    },
    {
      title: "5. Limitation of Liability",
      content: `UNDER NO CIRCUMSTANCES SHALL SCREENIFY, ITS LICENSORS, OR DEVELOPERS BE LIABLE FOR ANY DAMAGES, LOSSES, APP REJECTIONS, BRAND DAMAGE, OR BUSINESS INTERRUPTIONS RESULTING FROM THE USE OF, OR INABILITY TO USE, THE AI-GENERATED AND RENDERED CREATIVES, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH ISSUES.`
    },
    {
      title: "6. Contact Us",
      content: `If you require clarification on this AI Disclaimer, please reach out to our team at support@screenify.cloud.`
    }
  ];

  return (
    <main className="min-h-screen bg-background text-foreground grain">
      <div className="mx-auto max-w-3xl px-6 py-16">
        <Link
          to="/"
          className="mb-8 inline-flex items-center gap-2 text-sm text-muted-foreground transition-colors hover:text-foreground"
        >
          <svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M19 12H5M12 19l-7-7 7-7" />
          </svg>
          Back to Home
        </Link>

        <h1 className="font-display text-4xl sm:text-5xl mb-4">
          Legal <span className="italic text-lime">Disclaimer</span>
        </h1>
        <p className="mb-10 text-sm text-muted-foreground font-mono">
          Last updated: {lastUpdated}
        </p>

        <div className="space-y-10">
          {sections.map((section) => (
            <section key={section.title} className="border-b border-border/40 pb-8 last:border-0 last:pb-0">
              <h2 className="mb-3 font-mono text-xs uppercase tracking-widest text-lime font-bold">
                {section.title}
              </h2>
              <div className="text-sm leading-relaxed space-y-2">
                {renderLegalContent(section.content)}
              </div>
            </section>
          ))}
        </div>

        <div className="mt-14 border-t border-border pt-8">
          <p className="text-sm text-muted-foreground">
            Questions about this disclaimer? Reach out to us at{" "}
            <a
              href="mailto:support@screenify.cloud"
              className="text-foreground underline underline-offset-4 transition hover:text-lime"
            >
              support@screenify.cloud
            </a>
          </p>
        </div>
      </div>

      <footer className="border-t border-border">
        <div className="mx-auto max-w-6xl px-6 py-8 flex flex-wrap justify-between gap-4 text-xs text-muted-foreground">
          <span>&copy; {new Date().getFullYear()} Screenify</span>
          <Link to="/" className="transition-colors hover:text-foreground">
            Back to Home
          </Link>
        </div>
      </footer>
    </main>
  );
}
