import { createFileRoute, Link } from "@tanstack/react-router";
import { renderLegalContent } from "@/lib/legal-formatter";

export const Route = createFileRoute("/terms")({
  component: TermsPage,
});

function TermsPage() {
  const lastUpdated = "June 12, 2026";

  const sections = [
    {
      title: "1. Definitions",
      content: `In these Terms and Conditions:
      - "Screenify" ("we", "our", "us") refers to the SaaS platform and service operated by individual developer Adil Jakir Husen Shaikh, located in Mumbai, Maharashtra, India.
      - "Service" refers to the website located at screenify.dev, the application, and any associated features, content, products, or services.
      - "User" ("you", "your") refers to any individual or entity registering for, accessing, or using the Service.
      - "User Content" refers to any files, raw screenshots, logos, text, or other assets uploaded or input by the User into the Service.
      - "Generated Content" refers to the final storefront screenshots, templates, layouts, copywriting, or mockups generated by our AI-assisted design engine based on the User Content.`
    },
    {
      title: "2. Acceptance of Terms",
      content: `By creating an account, making a purchase, or otherwise accessing or using the Service, you confirm that you have read, understood, and agreed to be bound by these Terms and Conditions, our Privacy Policy, Cookie Policy, Refund Policy, and Acceptable Use Policy. If you do not agree to these terms, you are strictly prohibited from using the Service and must cease all access immediately.`
    },
    {
      title: "3. Eligibility Requirements",
      content: `To register for an account or use the Service, you must be at least 18 years of age (or the age of majority in your jurisdiction) and possess the full legal capacity to enter into a binding contract. If you are accepting these terms on behalf of a company, partnership, or other commercial entity, you represent and warrant that you have the legal authority to bind that entity to these Terms.`
    },
    {
      title: "4. User Accounts and Security",
      content: `Access to certain features of the Service requires account registration. You agree to: (a) provide accurate, current, and complete information during registration; (b) maintain the security and confidentiality of your credentials; and (c) immediately notify us of any unauthorized account access. You are solely responsible for all activities, charges, and actions that occur under your account. We reserve the right to suspend or terminate accounts that provide false details or violate these Terms.`
    },
    {
      title: "5. User Responsibilities & Permitted Use",
      content: `You are granted a limited, non-exclusive, non-transferable, revocable license to access and use the Service strictly for commercial purposes related to designing, previewing, and downloading Shopify App Store promotional screenshots. You agree to use the Service in full compliance with all applicable local, national, and international laws, as well as Shopify's platform terms.`
    },
    {
      title: "6. Prohibited Activities",
      content: `You represent and warrant that you will not use the Service for any unlawful or unauthorized activities. Prohibited activities include, but are not limited to:
      - Uploading User Content that is illegal, defamatory, fraudulent, threatening, or infringes on any third-party intellectual property.
      - Reverse engineering, decompiling, or attempting to extract the source code or underlying layout algorithms of the Service.
      - Using automated scripts, bots, spiders, or scrapers to extract data, content, or screenshots from the Service.
      - Flooding our servers or making excessive API calls that compromise service performance.
      - Attempting to bypass the payment flow, watermark protections, or security mechanisms.`
    },
    {
      title: "7. Intellectual Property Rights",
      content: `All rights, title, and interest in and to the Service, including the website design, layout, templates, color-presets, graphics, underlying software, and layout algorithms (excluding User Content), are and will remain the exclusive property of Screenify and its licensors. Screenify is protected by copyright, trademark, and trade secret laws.`
    },
    {
      title: "8. User Content & Uploaded Content Ownership",
      content: `You retain full intellectual property ownership of all User Content (such as raw app screenshots, brand logos, and custom text inputs) that you upload to Screenify. By uploading User Content, you grant Screenify a worldwide, royalty-free, non-exclusive, sublicensable license to process, store, resize, and transmit your User Content solely to generate your marketing creatives and perform the Service. We do not use your screenshots to train public AI models.`
    },
    {
      title: "9. Generated Content Ownership & License",
      content: `Once you unlock and download the Generated Content (the final 6-slide storefront graphics), Screenify grants you a perpetual, worldwide, fully paid-up, royalty-free, non-exclusive license to use, display, modify, and distribute the Generated Content for the purpose of promoting your software applications (such as on the Shopify App Store, product website, or marketing channels). You may not resell or bundle the Generated Content templates to third parties as stand-alone design templates.`
    },
    {
      title: "10. AI-Generated Content Disclaimer",
      content: `The Service utilizes advanced artificial intelligence models (such as OpenAI and Google Gemini) to generate copywriting suggestions (headlines, subheadlines, and features). Because AI technologies are probabilistic, you acknowledge and agree that:
      - The generated copy may occasionally contain inaccuracies, repetitive text, or trademarked names.
      - You are solely responsible for reviewing, proofreading, and editing all Generated Content before publishing it.
      - Screenify does not guarantee that the Generated Content will comply with Shopify's App Store guidelines or receive approval.
      - Screenify is not liable for any trademark disputes, brand damage, or rejections arising from your use of AI-generated copy.`
    },
    {
      title: "11. Subscriptions, Billing, and Pricing Changes",
      content: `Screenify offers both one-time generation/export purchases and recurring subscription tiers. By signing up for a paid plan, you agree to pay all applicable fees as they fall due.
      - **Billing Cycles**: Subscriptions are billed in advance on a recurring monthly or annual basis.
      - **Pricing Adjustments**: We reserve the right to modify our pricing tiers at any time. Any changes to subscription pricing will take effect at the start of the next billing cycle, and we will provide you with at least 30 days' advance notice.`
    },
    {
      title: "12. Payment Processing & Fulfillment",
      content: `All payments, checkouts, and recurring subscriptions are processed securely by Dodo Payments, our third-party payment gateway and Merchant of Record. By making a purchase, you agree to comply with Dodo Payments' customer terms and privacy policies. Screenify does not directly store or access your credit card numbers or banking credentials.
      - **Fulfillment & Delivery**: All purchases, including credits and subscriptions, are delivered instantly online to the User's dashboard. Upon successful payment verification, high-resolution downloads and Pro features are unlocked immediately. There are no physical shipping requirements.`
    },
    {
      title: "13. Service Availability and Modifications",
      content: `We strive to ensure continuous availability of the Service. However, you acknowledge that access may occasionally be interrupted for scheduled maintenance, updates, or unplanned server outages. We reserve the right to modify, suspend, or discontinue any feature, template style, or aspect of the Service at any time without liability.`
    },
    {
      title: "14. Account Suspension and Termination",
      content: `We reserve the right to suspend or terminate your account and block your access to the Service immediately, without prior notice or liability, if you violate these Terms, breach our Acceptable Use Policy, engage in fraudulent payment activity, or fail to pay subscription charges.`
    },
    {
      title: "15. Disclaimer of Warranties",
      content: `THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY LAW, SCREENIFY DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, ACCURATE, ERROR-FREE, OR METRIC-DRIVEN.`
    },
    {
      title: "16. Limitation of Liability",
      content: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL SCREENIFY, ITS DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION LOSS OF PROFITS, DATA, REVENUE, GOODWILL, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR IN CONNECTION WITH YOUR ACCESS TO OR USE OF THE SERVICE, REGARDLESS OF THE LEGAL THEORY. IN NO EVENT SHALL SCREENIFY'S AGGREGATE LIABILITY EXCEED THE TOTAL AMOUNT PAID BY YOU TO SCREENIFY IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.`
    },
    {
      title: "17. Indemnification",
      content: `You agree to defend, indemnify, and hold harmless Screenify and its affiliates, directors, officers, employees, and agents from and against any claims, damages, liabilities, losses, costs, or expenses (including reasonable attorneys' fees) arising out of or resulting from: (a) your use of and access to the Service; (b) your violation of these Terms; (c) your User Content; or (d) any claim that your screenshots or brand logos infringe the intellectual property rights of any third party.`
    },
    {
      title: "18. Governing Law and Jurisdiction",
      content: `These Terms and Conditions shall be governed by, and construed in accordance with, the laws of Maharashtra, India, without regard to its conflict of law principles. Any legal action or proceeding arising under these Terms shall be brought exclusively in the courts located in Mumbai, India.`
    },
    {
      title: "19. Dispute Resolution & Class Action Waiver",
      content: `Any dispute, controversy, or claim arising out of or relating to these Terms, including the determination of the scope or applicability of this agreement to arbitrate, shall be settled by binding arbitration in accordance with the commercial arbitration rules of the American Arbitration Association (AAA). 
      - **Class Action Waiver**: You and Screenify agree that any dispute resolution proceedings will be conducted solely on an individual basis and not in a class, consolidated, or representative action.`
    },
    {
      title: "20. Service Data Retention",
      content: `We retain your account details and upload references in accordance with our Privacy Policy. If your account is terminated or remains inactive for more than 12 consecutive months, we reserve the right to delete your user configurations, uploaded screenshots, and history from our active databases without liability.`
    },
    {
      title: "21. Contact Information",
      content: `If you have any questions, concerns, or legal notices regarding these Terms, please contact us at:
      - **Developer**: Adil Jakir Husen Shaikh
      - **Location**: Mumbai, Maharashtra, India
      - **Email**: support@screenify.cloud`
    }
  ];

  return (
    <main className="min-h-screen bg-background text-foreground grain">
      <div className="mx-auto max-w-3xl px-6 py-16">
        <Link
          to="/"
          className="mb-8 inline-flex items-center gap-2 text-sm text-muted-foreground transition-colors hover:text-foreground"
        >
          <svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M19 12H5M12 19l-7-7 7-7" />
          </svg>
          Back to Home
        </Link>

        <h1 className="font-display text-4xl sm:text-5xl mb-4">
          Terms & <span className="italic text-lime">Conditions</span>
        </h1>
        <p className="mb-10 text-sm text-muted-foreground font-mono">
          Last updated: {lastUpdated}
        </p>

        <div className="space-y-10">
          {sections.map((section) => (
            <section key={section.title} className="border-b border-border/40 pb-8 last:border-0 last:pb-0">
              <h2 className="mb-3 font-mono text-xs uppercase tracking-widest text-lime font-bold">
                {section.title}
              </h2>
              <div className="text-sm leading-relaxed space-y-2">
                {renderLegalContent(section.content)}
              </div>
            </section>
          ))}
        </div>

        <div className="mt-14 border-t border-border pt-8">
          <p className="text-sm text-muted-foreground">
            Questions about these terms? Reach out to us at{" "}
            <a
              href="mailto:support@screenify.cloud"
              className="text-foreground underline underline-offset-4 transition hover:text-lime"
            >
              support@screenify.cloud
            </a>
          </p>
        </div>
      </div>

      <footer className="border-t border-border">
        <div className="mx-auto max-w-6xl px-6 py-8 flex flex-wrap justify-between gap-4 text-xs text-muted-foreground">
          <span>&copy; {new Date().getFullYear()} Screenify by Adil Jakir Husen Shaikh</span>
          <Link to="/" className="transition-colors hover:text-foreground">
            Back to Home
          </Link>
        </div>
      </footer>
    </main>
  );
}
